### ISSUE TITLE
Needs a tagline, READMe, etc.

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/freshly#1]
Hey, what's the status of this project? And what is this project?

**Comment by prayerslayer** [comment]
It's an award-winning prototype from Hackweek IV. Status: stale. We might update it to a point where it's usable with fake data.

**Comment by lasomethingsomething** [comment]
Cool. For now, can you move to GHE?

**Comment by prayerslayer** [comment]
Closing this for now.
